<a href="https://colab.research.google.com/github/Satyamjat/python.pandas/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,4])
b=np.array([3,4,5])

print(a*b)


[ 3  8 20]


In [ ]:
import numpy as np
c =np.array([[1.0,2.0,.9,4.0],[6.0,.2,7.0,2.0]])
print(c)

[[1.  2.  0.9 4. ]
 [6.  0.2 7.  2. ]]


In [ ]:
#get dimention
print(c.ndim)

2


In [ ]:
#get shampe
print(c.shape)

(2, 4)


In [ ]:
a1=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a1)
print(a1[1,2])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
10


In [ ]:
#print a row
print(a1[1,:])

[ 8  9 10 11 12 13 14]


In [ ]:
#print a column
print(a1[:,1])

[2 9]


In [ ]:
#[row,start:end:step]
print(a1[0,1:6:2])
print(a1[1,1:10:1])

[2 4 6]
[ 9 10 11 12 13 14]


In [ ]:
#zeros matrix and once and any full
a2=np.zeros((2,3))
print(a2)
a3=np.ones((2,3))
print(a3)
a4=np.full((2,3),3,dtype='float32')
print(a4)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [ ]:
#random deciaml number
b1=np.random.rand(1,3,3)
print(b1)
b2=np.random.randint(100,150,size=(3,2))
print(b2)

[[[0.5488135  0.71518937 0.60276338]
  [0.54488318 0.4236548  0.64589411]
  [0.43758721 0.891773   0.96366276]]]
[[101 138]
 [139 123]
 [146 124]]


In [ ]:
np.random.seed(0)

In [ ]:
#identity matrix
c1=np.identity(3)
print(c1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#repeat an array
arr=np.array([[1,2,3]])
a1rr=np.repeat(arr,3,axis=0)
print(a1rr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# patttern
output=np.ones((5,5))
# print(output)

z=np.zeros((3,3))
# print(z)
z[1,1]=9
# print(z)

output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# op on array
a=np.array([1,2,3,4])
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a**2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [ ]:
a=np.array([4,3,2,1])
b=np.array([1,2,3,4])
print(a+b)

[5 5 5 5]


In [ ]:
#multiply matrix
a=np.ones((2,3))
b=np.full((3,2),2)
print(a)
print(b)

c=np.matmul(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [ ]:
# reshape
before=np.array([[1,2,3,4],[4,5,6,7]])
print(before)
after=before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [4 5 6 7]]
[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [ ]:
# vertical stack
v1=np.array([2,34,5,6,2])
v2=np.array([3,4,5,6,45])
V=np.vstack([v1,v2,v2,v1])
print(V)



[[ 2 34  5  6  2]
 [ 3  4  5  6 45]
 [ 3  4  5  6 45]
 [ 2 34  5  6  2]]


In [ ]:
#horizontal stack
h1=np.array([2,34,5,6,2])
h2=np.array([3,4,5,6,45])
H=np.hstack((h1,h2,h2))
print(H)

[ 2 34  5  6  2  3  4  5  6 45]


In [ ]:
filedata =np.genfromtxt('/content/data.txt',delimiter=',')
filedata1=np.nan_to_num(filedata).astype('int32')
print(filedata1)

In [ ]:
filedata =np.genfromtxt('data.txt',delimiter=',')
# Fill NaN values with 0 before converting to int32
filedata1 = np.nan_to_num(filedata).astype('int32')
print(filedata1)

In [ ]:
print(filedata1>50)
print(filedata1[filedata1>50])